### ISSUE TITLE
Will it work with totk 1.1.1?

### ISSUE THREAD

**Issue by fmpallini** [Wollnashorn/switch-mods#1]
My questions is if the memory addresses used by the fix still be valid for update 1.1.1 of totk. Regards!

**Comment by Wollnashorn** [comment]
Hi, I just added an updated version for 1.1.1. Luckily it is pretty easy to update it, as the instruction can be easily be pattern searched in Ghidra.

**Comment by Wollnashorn** [comment]
I realized I did a mistake in the first version of the AF mod for 1.1.1. I forgot to update the nsobid and so it wasn't working. I fixed it now and updated to 1.1.2

**Comment by fmpallini** [comment]
cool, rapid fix. hey it seems that current version is missing a 0 at the nsobid?

**Comment by Wollnashorn** [comment]
> cool, rapid fix. hey it seems that current version is missing a 0 at the nsobid?

I used the nsobid Yuzu prints in the logs, I believe the trailing zeroes get discarded and it should be fine. This time I also actually tested it and confirmed it working. Bugs me I messed it up last update 😅 Have fun!
