### ISSUE TITLE
Is it possible to disable FXAA in BOTW?

### ISSUE THREAD

**Issue by zhm86** [Wollnashorn/switch-mods#2]

**Comment by Wollnashorn** [comment]
Yup, [here you go!](https://github.com/Wollnashorn/switch-mods/tree/master/01007EF00011E000)
You owe me a Red Bull 😂

![fxaa_on](https://github.com/Wollnashorn/switch-mods/assets/17367726/2c756ebd-b085-40e6-b907-64ffa37c1dca)
![fxaa_off](https://github.com/Wollnashorn/switch-mods/assets/17367726/5b89e8e2-8a69-40d0-b6ae-a827a8996849)
